version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:13-alpine
    container_name: docusense_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: docusense
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docusense_api
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend/templates:/app/templates
    depends_on:
      postgres:
        condition: service_healthy

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docusense_web
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  postgres_data: